name: Peiter C Hergert
favicon: null
layout_spectrum: 0.9822
typography_spectrum: 0.21501
title: Motion Director
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#767a7d'
    - '#4e4900'
    - '#bd061b'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
