name: Peiter C Hergert
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21
title: Motion Director
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#4c137c'
    - '#f7f5fa'
    - '#a287a8'
    - '#bebcbc'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
