name: SuperHawt5000
favicon: null
layout_spectrum: 0.5056672035716474
typography_spectrum: 0.08121063350699842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04153861361555755
  lightness: 0.9811728324275464
  saturation: 0.9429371752776206
  rhythmicContrast: 0.4723576509859413
purpose: []
